# Generated by Django 4.1.7 on 2023-04-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribes',
            new_name='subscribers',
        ),
    ]
